### ISSUE TITLE
The triangle_* tests fail on  my system

### ISSUE THREAD

**Issue by nicokoch** [tomaka/glium#1244]
```
cargo test triangle
[...]skipping some bloat lines[...]

Running target/debug/indices-939bdd9e70e3f0a4

running 6 tests
test triangle_fan_noindices ... FAILED
test triangle_strip ... FAILED
test triangle_strip_noindices ... FAILED
test triangle_fan ... FAILED
test triangles_list_noindices ... FAILED
test triangles_list ... FAILED

failures:

---- triangle_fan_noindices stdout ----
        thread 'triangle_fan_noindices' panicked at 'assertion failed: `(left == right)` (left: `(0, 0, 0, 0)`, right: `(255, 0, 0, 255)`)', tests/indices.rs:266


---- triangle_strip stdout ----
        thread 'triangle_strip' panicked at 'assertion failed: `(left == right)` (left: `(0, 0, 0, 0)`, right: `(255, 0, 0, 255)`)', tests/indices.rs:103


---- triangle_strip_noindices stdout ----
        thread 'triangle_strip_noindices' panicked at 'assertion failed: `(left == right)` (left: `(0, 0, 0, 0)`, right: `(255, 0, 0, 255)`)', tests/indices.rs:238


---- triangle_fan stdout ----
        thread 'triangle_fan' panicked at 'assertion failed: `(left == right)` (left: `(0, 0, 0, 0)`, right: `(255, 0, 0, 255)`)', tests/indices.rs:130


---- triangles_list_noindices stdout ----
        thread 'triangles_list_noindices' panicked at 'assertion failed: `(left == right)` (left: `(0, 0, 0, 0)`, right: `(255, 0, 0, 255)`)', tests/indices.rs:212


---- triangles_list stdout ----
       thread 'triangles_list' panicked at 'assertion failed: `(left == right)` (left: `(0, 0, 0, 0)`, right: `(255, 0, 0, 255)`)', tests/indices.rs:77



failures:
    triangle_fan
    triangle_fan_noindices
    triangle_strip
    triangle_strip_noindices
    triangles_list
    triangles_list_noindices

test result: FAILED. 0 passed; 6 failed; 0 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', ../src/libtest/lib.rs:255
```
I noticed this isn't happening on travis-ci, so it actually might be a driver bug. I'm using the i965 driver. My OpenGL system info:

```
glxinfo | grep -i opengl  
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.6.7
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.6.7
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 10.6.7
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```

**Comment by tomaka** [comment]
That's probably because of #310
