### ISSUE TITLE
'arithmetic operation overflowed' OpenGL error during initialization

### ISSUE THREAD

**Issue by TheNeikos** [tomaka/glium#1298]
```
neikos@celestias-palace ~/p/r/rust-gg (add-window_module) [101]> env RUST_BACKTRACE=1 cargo run --example simple
     Running `target/debug/examples/simple`
glium has triggered an OpenGL error during initialization. Please report this error: https://github.com/tomaka/glium/issues
thread '<main>' panicked at 'arithmetic operation overflowed', src/event.rs:30
stack backtrace:
   1:     0x7fd1d87542be - sys::backtrace::write::ha67a6a2049d22fadIvs
   2:     0x7fd1d87579c6 - panicking::on_panic::hfa4bf0215983f759lzx
   3:     0x7fd1d874f36e - rt::unwind::begin_unwind_inner::ha1b5da93bdf7e8ffC0w
   4:     0x7fd1d874f936 - rt::unwind::begin_unwind_fmt::hac9e09b20e42a51cIZw
   5:     0x7fd1d8757396 - rust_begin_unwind
   6:     0x7fd1d877c3b4 - panicking::panic_fmt::hd75b6cee85f3afe4SgC
   7:     0x7fd1d877bd9d - panicking::panic::h25435899636f1091pfC
   8:     0x7fd1d8555bf5 - event::step::fixed::h3367868930290687227
                        at src/event.rs:30
   9:     0x7fd1d8555a93 - event::step::fixed_60::h11065430683454575616
                        at src/event.rs:42
  10:     0x7fd1d8539f3b - main::h013698df486c2431iaa
                        at examples/simple.rs:11
  11:     0x7fd1d87572ed - __rust_try
  12:     0x7fd1d875968a - rt::lang_start::hff4eb66c456e4a8ehux
  13:     0x7fd1d85565cb - main
  14:     0x7fd1d7d6c60f - __libc_start_main
  15:     0x7fd1d8539d98 - _start
  16:                0x0 - <unknown>
An unknown error occurred

To learn more, run the command again with --verbose.
```

The code:

```
extern crate gg;
extern crate glium;

use glium::DisplayBuild;
use gg::event::step::fixed_60;

fn main() {
    let display = glium::glutin::WindowBuilder::new().build_glium().unwrap();

    fixed_60(|_dt| {
        use gg::event::StepResult;
        for ev in display.poll_events() {
            match ev {
                glium::glutin::Event::Closed => return StepResult::Stop,
                _ => ()
            }
        }
        return StepResult::Continue;
    });

}
```

I have also commented out my loop and then I just get this error:

```
neikos@celestias-palace ~/p/r/rust-gg (add-window_module) [1]> env RUST_BACKTRACE=1 cargo run --example simple
   Compiling gg v0.1.0 (file:///home/neikos/projects/rust/rust-gg)
examples/simple.rs:5:5: 5:30 warning: unused import, #[warn(unused_imports)] on by default
examples/simple.rs:5 use gg::event::step::fixed_60;
                         ^~~~~~~~~~~~~~~~~~~~~~~~~
examples/simple.rs:8:9: 8:16 warning: unused variable: `display`, #[warn(unused_variables)] on by default
examples/simple.rs:8     let display = glium::glutin::WindowBuilder::new().build_glium().unwrap();
                             ^~~~~~~
     Running `target/debug/examples/simple`
glium has triggered an OpenGL error during initialization. Please report this error: https://github.com/tomaka/glium/issues
```

I am using stable rust 1.3

**Comment by TheNeikos** [comment]
Same thing if I launch `teapot.rs`:

```
neikos@celestias-palace ~/p/r/glium (master)> cargo run --example teapot
     Running `target/debug/examples/teapot`
glium has triggered an OpenGL error during initialization. Please report this error: https://github.com/tomaka/glium/issues

```
