### ISSUE TITLE
gpgpu example doesn't run

### ISSUE THREAD

**Issue by am0d** [tomaka/glium#1310]
I get the following output when I try executing the compute shader example:

    thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("0(5) : error C0000: syntax error, unexpected \';\', expecting \"::\" at token \";\"\n")', ../src/libcore\result.rs:731
    Process didn't exit successfully: `target\debug\examples\gpgpu.exe` (exit code: 101)

I can't tell if this is due to my machine setup, or a bug in the compute shader program, since I've never worked with compute shaders before.

**Comment by luxvio** [comment]
Same here, never used it ... but `glxinfo` shows this:

```text
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 960/PCIe/SSE2
OpenGL core profile version string: 4.4.0 NVIDIA 355.11
OpenGL core profile shading language version string: 4.40 NVIDIA via Cg compiler
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5.0 NVIDIA 355.11
OpenGL shading language version string: 4.50 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 NVIDIA 355.11
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
[snip]
    GL_ARB_compressed_texture_pixel_storage, GL_ARB_compute_shader, 
    GL_ARB_compute_variable_group_size, GL_ARB_conditional_render_inverted, 
    GL_NV_blend_square, GL_NV_command_list, GL_NV_compute_program5, 
    GL_ARB_compressed_texture_pixel_storage, GL_ARB_compute_shader, 
    GL_ARB_compute_variable_group_size, GL_ARB_conditional_render_inverted, 
    GL_NV_blend_square, GL_NV_command_list, GL_NV_compute_program5, 
```

**Comment by tomaka** [comment]
@luxvio That's a weird problem.

Could you add this code here: https://github.com/tomaka/glium/blob/master/src/program/shader.rs#L211

```rust
println!("{:?}", ctxt.get_version());
println!("{:?}", ctxt.get_extensions());
```

...and check what is printed?

**Comment by luxvio** [comment]
Ok, that passage ended up like this:

```rust
        gl::COMPUTE_SHADER => {
	   println!("{:?}", ctxt.get_version());
	   println!("{:?}", ctxt.get_extensions());
            if !(ctxt.get_version() >= &Version(Api::Gl, 4, 3))
                && !(ctxt.get_version() >= &Version(Api::GlEs, 3, 1))
                && !ctxt.get_extensions().gl_arb_compute_shader
            {
                return false;
            }
        },
```

And the result is this one:

```
    Running `target/debug/examples/gpgpu`
Version(Gl, 2, 1)
ExtensionsList { gl_amd_depth_clamp_separate: false, gl_amd_query_buffer_object: false, gl_angle_framebuffer_multisample: false, gl_apple_framebuffer_multisample: false, gl_apple_sync: false, gl_apple_vertex_array_object: true, gl_arb_bindless_texture: false, gl_arb_buffer_storage: false, gl_arb_compute_shader: false, gl_arb_copy_buffer: true, gl_arb_debug_output: true, gl_arb_depth_clamp: true, gl_arb_depth_texture: true, gl_arb_direct_state_access: false, gl_arb_draw_buffers: true, gl_arb_draw_elements_base_vertex: true, gl_arb_compatibility: false, gl_arb_es2_compatibility: false, gl_arb_es3_compatibility: false, gl_arb_es3_1_compatibility: false, gl_arb_es3_2_compatibility: false, gl_arb_fragment_shader: true, gl_arb_framebuffer_no_attachments: false, gl_arb_framebuffer_object: true, gl_arb_framebuffer_srgb: false, gl_arb_geometry_shader4: false, gl_arb_get_programy_binary: true, gl_arb_gpu_shader_fp64: false, gl_arb_gpu_shader_int64: false, gl_arb_instanced_arrays: false, gl_arb_internalformat_query: false, gl_arb_invalidate_subdata: true, gl_arb_occlusion_query: true, gl_arb_occlusion_query2: true, gl_arb_pixel_buffer_object: true, gl_arb_program_interface_query: true, gl_arb_query_buffer_object: false, gl_arb_map_buffer_range: true, gl_arb_multi_draw_indirect: false, gl_arb_provoking_vertex: true, gl_arb_robustness: true, gl_arb_robust_buffer_access_behavior: false, gl_arb_sampler_objects: true, gl_arb_shader_image_load_store: false, gl_arb_shader_objects: true, gl_arb_shader_storage_buffer_object: false, gl_arb_sync: true, gl_arb_tessellation_shader: false, gl_arb_texture_buffer_object: false, gl_arb_texture_buffer_object_rgb32: false, gl_arb_texture_compression_bptc: true, gl_arb_texture_cube_map: true, gl_arb_texture_cube_map_array: false, gl_arb_texture_float: true, gl_arb_texture_multisample: false, gl_arb_texture_non_power_of_two: true, gl_arb_texture_rg: true, gl_arb_texture_rgb10_a2ui: false, gl_arb_texture_stencil8: false, gl_arb_texture_storage: true, gl_arb_timer_query: false, gl_arb_transform_feedback3: false, gl_arb_uniform_buffer_object: false, gl_arb_vertex_array_object: true, gl_arb_vertex_buffer_object: true, gl_arb_vertex_half_float: false, gl_arb_vertex_shader: true, gl_arb_vertex_type_10f_11f_11f_rev: false, gl_arb_vertex_type_2_10_10_10_rev: false, gl_arm_rgba8: false, gl_ati_meminfo: false, gl_ati_draw_buffers: true, gl_ati_texture_float: true, gl_ext_blend_minmax: true, gl_ext_buffer_storage: false, gl_ext_debug_marker: false, gl_ext_direct_state_access: false, gl_ext_disjoint_timer_query: false, gl_ext_framebuffer_blit: true, gl_ext_framebuffer_object: true, gl_ext_framebuffer_multisample: false, gl_ext_framebuffer_srgb: false, gl_ext_geometry_shader: false, gl_ext_geometry_shader4: false, gl_ext_gpu_shader4: false, gl_ext_multi_draw_indirect: false, gl_ext_multisampled_render_to_texture: false, gl_ext_occlusion_query_boolean: false, gl_ext_packed_depth_stencil: true, gl_ext_packed_float: false, gl_ext_primitive_bounding_box: false, gl_ext_provoking_vertex: true, gl_ext_robustness: false, gl_ext_srgb_write_control: false, gl_ext_texture3d: true, gl_ext_texture_array: true, gl_ext_texture_buffer: false, gl_ext_texture_buffer_object: false, gl_ext_texture_compression_s3tc: true, gl_ext_texture_cube_map: true, gl_ext_texture_cube_map_array: false, gl_ext_texture_filter_anisotropic: true, gl_ext_texture_integer: false, gl_ext_texture_shared_exponent: true, gl_ext_texture_snorm: false, gl_ext_texture_srgb: true, gl_ext_transform_feedback: false, gl_gremedy_string_marker: false, gl_khr_debug: true, gl_khr_context_flush_control: true, gl_khr_robustness: false, gl_khr_robust_buffer_access_behavior: false, gl_nv_fbo_color_attachments: false, gl_nv_conditional_render: true, gl_nv_copy_buffer: false, gl_nv_depth_clamp: true, gl_nv_framebuffer_multisample: false, gl_nv_half_float: false, gl_nv_internalformat_sample_query: false, gl_nv_pixel_buffer_object: false, gl_nv_read_depth: false, gl_nv_read_stencil: false, gl_nv_read_depth_stencil: false, gl_nv_texture_array: false, gl_nv_vertex_attrib_integer_64bit: false, gl_nvx_gpu_memory_info: false, gl_oes_depth_texture: false, gl_oes_draw_elements_base_vertex: false, gl_oes_element_index_uint: false, gl_oes_fixed_point: false, gl_oes_geometry_shader: false, gl_oes_packed_depth_stencil: false, gl_oes_primitive_bounding_box: false, gl_oes_rgb8_rgba8: false, gl_oes_stencil1: false, gl_oes_stencil4: false, gl_oes_tessellation_shader: false, gl_oes_texture_3d: false, gl_oes_texture_buffer: false, gl_oes_texture_cube_map_array: false, gl_oes_texture_stencil8: false, gl_oes_texture_storage_multisample_2d_array: false, gl_oes_vertex_array_object: false, gl_oes_vertex_half_float: false, gl_oes_vertex_type_10_10_10_2: false }
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: ShaderTypeNotSupported', ../src/libcore/result.rs:736
An unknown error occurred

```

I think I saw this before when doing some opengl learning with an nvidia card ... I really had to explicitly ask the version if I wanted anything >3.3 with any helper library (glad, glfw, etc).

I made some poking around with gl-rs and glutin (before knowing of glium) and used to work it around with: 

```rust
.with_gl_profile(glutin::GlProfile::Core)
```

with window builder and all purrfect. But seems that Headless somehow is picking a lower version, even if I make things like adding this to the builder:

```rust
.with_gl(glutin::GlRequest::Specific(glutin::Api::OpenGl, (4, 3)))
```

or
 
```rust
.with_gl(glutin::GlRequest::Latest)
```

Anything else I can help with?  I looked at some warnings compiling with rust 1.4, so in the meanwhile I'll see to tackle them and see if I can get familiar with the code

Ty

**Comment by tomaka** [comment]
Ah! That's because headless contexts on Linux automatically use OSMesa, which only supports OpenGL 2.1.

It should try to use EGL or GLX pbuffers, but this is not implemented yet :-/

**Comment by luxvio** [comment]
Question: can I make a PR making the workaround with a comment explaining it?
also ... there's  warnings on unused results:

```
src/texture/any.rs:1296:9: 1296:96 warning: unused result which must be used, #[warn(unused_must_use)] on by default
src/texture/any.rs:1296         ops::read(&mut ctxt, &fbo::RegularAttachment::Texture(*self), &rect, &mut data, false);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/texture/any.rs:1314:9: 1314:91 warning: unused result which must be used, #[warn(unused_must_use)] on by default
src/texture/any.rs:1314         ops::read(&mut ctxt, &fbo::RegularAttachment::Texture(*self), &rect, dest, false);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/context/mod.rs:472:9: 473:26 warning: unused result which must be used, #[warn(unused_must_use)] on by default
src/context/mod.rs:472         ops::read(&mut ctxt, ops::Source::DefaultFramebuffer(gl::FRONT_LEFT), &rect, &mut data,
```
ignoring the result is intended behavior or WIP? I wasn't sure if I could also include a `let _ = [snip]`  or if writing a custom error/returning result would be more appropiate.

Ty  :D

**Comment by tomaka** [comment]
You can make a comment explaining a work-around, but don't touch the code please. Using a headless renderer is the correct thing to do. An invisible window is a hack.

**Comment by luxvio** [comment]
I feel like it's pointless to argue how a compiling, with no warnings comments notes docs or whatsoever, headless renderer is also a hack or possibly worst. I won't touch no code, don't worry *sigh
