### ISSUE TITLE
GL_INVALID_FRAMBUFFER:OPERATION in glReadPixels

### ISSUE THREAD

**Issue by Roxxik** [tomaka/glium#1396]
I encountered something funny while working with glium:

    Mesa 11.1.0 implementation error: gen7_update_renderbuffer_surface: renderbuffer format MESA_FORMAT_RGB_SINT32 unsupported

    Please report at https://bugs.freedesktop.org/enter_bug.cgi?product=Mesa
    Debug message with high or medium severity: `GL_INVALID_FRAMEBUFFER_OPERATION in glClear(incomplete framebuffer)`.
    Please report this error: https://github.com/tomaka/glium/issues
    Backtrace:
       1 - 0x55e67ebaa163
             _ZN9backtrace9backtrace9libunwind5traceE at /home/roxxik/.cargo/registry/src/github.com-88ac128001ac3a9a/backtrace-0.1.8/src/backtrace/libunwind.rs:54
             _ZN9backtrace9backtrace5traceE at /home/roxxik/.cargo/registry/src/github.com-88ac128001ac3a9a/backtrace-0.1.8/src/backtrace/mod.rs:67
       2 - 0x55e67ea3d5c9
             _ZN5glium7context22default_debug_callbackE at /home/roxxik/repos/glium/src/context/mod.rs:798
       3 - 0x55e67ea3d699
             _ZN156fn$LP$debug..Source$C$$u20$debug..MessageType$C$$u20$debug..Severity$C$$u20$u32$C$$u20$bool$C$$u20$$RF$str$RP$$u20$$u7b$context..default_debug_callback$u7d$21fn_pointer_shim.7158417ha294efbf0d04ac16E at <unknown>:??
       4 - 0x55e67eabe8b2
             _ZN372extern$u20$$u22$rust.call$u22$$u20$fn$LP$$RF$mut$u20$for$LT$$u27$r$GT$$u20$core..ops..FnMut$LP$debug..Source$C$$u20$debug..MessageType$C$$u20$debug..Severity$C$$u20$u32$C$$u20$bool$C$$u20$$RF$$u27$r$u20$str$RP$$u20$$u2b$$u20$$u27$static$C$$u20$$LP$debug..Source$C$$u20$debug..MessageType$C$$u20$debug..Severity$C$$u20$u32$C$$u20$bool$C$$u20$$RF$$u27$static$u20$str$RP$$RP$17object_shim.7754817h8d94c2ee80a483caE at <unknown>:??
       5 - 0x55e67eabe7e9
             _ZN5glium7context19init_debug_callback16callback_wrapperE at /home/roxxik/repos/glium/src/context/mod.rs:887
       6 - 0x55e67eabdf94
             _ZN7context19init_debug_callback16callback_wrapper20h60fcaf4a1f73ead9hHSE at <unknown>:??
       7 - 0x7f5735ee75e8
             <unknown> at <unknown>:??
       8 - 0x55e67eaefdde
             _ZN5glium2gl2Gl5ClearE at target/debug/build/glium-1d288aab5bb0a2d4/out/gl_bindings.rs:10668
       9 - 0x55e67ea5858c
             _ZN5glium3ops5clear5clearE at /home/roxxik/repos/glium/src/ops/clear.rs:121
      10 - 0x55e67e9c8ffe
             _ZN9xxxxxxxxxx11framebuffer29SimpleFrameBuffer<'a>.Surface5clearE at /home/roxxik/repos/glium/src/framebuffer/mod.rs:274
      11 - 0x55e67e9c8efe
             _ZN9xxxxxxxxxx7Surface50clear_depth<glium::framebuffer::SimpleFrameBuffer>E at /home/roxxik/repos/glium/src/lib.rs:678
      12 - 0x55e67e9aff63
             _ZN9xxxxxxxxxx6render7picking6Picker249draw<(&glium::vertex::buffer::VertexBuffer<xxxxxxxxxx::render::cube::CubeVertex>, glium::vertex::PerInstance),&glium::index::buffer::IndexBuffer<u16>,glium::uniforms::uniforms::UniformsStorage<[[f32; 4]; 4], glium::uniforms::uniforms::EmptyUniforms>>E at src/render/picking.rs:111
      13 - 0x55e67e90a5ab
             _ZN9xxxxxxxxxx6render8Renderer9game_loopE at src/render/mod.rs:157
      14 - 0x55e67e9f4a61
             _ZN9xxxxxxxxxx4mainE at src/main.rs:36
      15 - 0x55e67ece8894
             _ZN10sys_common6unwind3try6try_fn21h12978415923074316437E at <unknown>:??
      16 - 0x55e67ece6238
             __rust_try at <unknown>:??
      17 - 0x55e67ece852f
             _ZN2rt10lang_start20hbeb1bf39635abdcc9kxE at <unknown>:??
      18 - 0x55e67e9f4e99
             main at <unknown>:??
      19 - 0x7f573d1e060f
             __libc_start_main at <unknown>:??
      20 - 0x55e67e8b4908
             _start at <unknown>:??
      21 - 0x0
             <unknown> at <unknown>:??

    Debug message with high or medium severity: `GL_INVALID_FRAMEBUFFER_OPERATION in glDrawElementsInstanced(incomplete framebuffer)`.
    Please report this error: https://github.com/tomaka/glium/issues
    Backtrace:
       1 - 0x55e67ebaa163
             _ZN9backtrace9backtrace9libunwind5traceE at /home/roxxik/.cargo/registry/src/github.com-88ac128001ac3a9a/backtrace-0.1.8/src/backtrace/libunwind.rs:54
             _ZN9backtrace9backtrace5traceE at /home/roxxik/.cargo/registry/src/github.com-88ac128001ac3a9a/backtrace-0.1.8/src/backtrace/mod.rs:67
       2 - 0x55e67ea3d5c9
             _ZN5glium7context22default_debug_callbackE at /home/roxxik/repos/glium/src/context/mod.rs:798
       3 - 0x55e67ea3d699
             _ZN156fn$LP$debug..Source$C$$u20$debug..MessageType$C$$u20$debug..Severity$C$$u20$u32$C$$u20$bool$C$$u20$$RF$str$RP$$u20$$u7b$context..default_debug_callback$u7d$21fn_pointer_shim.7158417ha294efbf0d04ac16E at <unknown>:??
       4 - 0x55e67eabe8b2
             _ZN372extern$u20$$u22$rust.call$u22$$u20$fn$LP$$RF$mut$u20$for$LT$$u27$r$GT$$u20$core..ops..FnMut$LP$debug..Source$C$$u20$debug..MessageType$C$$u20$debug..Severity$C$$u20$u32$C$$u20$bool$C$$u20$$RF$$u27$r$u20$str$RP$$u20$$u2b$$u20$$u27$static$C$$u20$$LP$debug..Source$C$$u20$debug..MessageType$C$$u20$debug..Severity$C$$u20$u32$C$$u20$bool$C$$u20$$RF$$u27$static$u20$str$RP$$RP$17object_shim.7754817h8d94c2ee80a483caE at <unknown>:??
       5 - 0x55e67eabe7e9
             _ZN5glium7context19init_debug_callback16callback_wrapperE at /home/roxxik/repos/glium/src/context/mod.rs:887
       6 - 0x55e67eabdf94
             _ZN7context19init_debug_callback16callback_wrapper20h60fcaf4a1f73ead9hHSE at <unknown>:??
       7 - 0x7f5735ee75e8
             <unknown> at <unknown>:??
       8 - 0x7f5735ec6540
             <unknown> at <unknown>:??
       9 - 0x7f5735eaf0b0
             <unknown> at <unknown>:??
      10 - 0x7f5735eaf53c
             <unknown> at <unknown>:??
      11 - 0x7f5735eafc7f
             <unknown> at <unknown>:??
      12 - 0x7f5735fe39aa
             <unknown> at <unknown>:??
      13 - 0x55e67e9dbc5c
             _ZN9xxxxxxxxxx2gl2Gl21DrawElementsInstancedE at target/debug/build/glium-1d288aab5bb0a2d4/out/gl_bindings.rs:11042
      14 - 0x55e67e9cb59f
             _ZN9xxxxxxxxxx3ops4draw209draw<glium::uniforms::uniforms::UniformsStorage<[[f32; 4]; 4], glium::uniforms::uniforms::EmptyUniforms>,(&glium::vertex::buffer::VertexBuffer<xxxxxxxxxx::render::cube::CubeVertex>, glium::vertex::PerInstance)>E at /home/roxxik/repos/glium/src/ops/draw.rs:225
      15 - 0x55e67e9c98bd
             _ZN9xxxxxxxxxx11framebuffer29SimpleFrameBuffer<'a>.Surface249draw<(&glium::vertex::buffer::VertexBuffer<xxxxxxxxxx::render::cube::CubeVertex>, glium::vertex::PerInstance),&glium::index::buffer::IndexBuffer<u16>,glium::uniforms::uniforms::UniformsStorage<[[f32; 4]; 4], glium::uniforms::uniforms::EmptyUniforms>>E at /home/roxxik/repos/glium/src/framebuffer/mod.rs:316
      16 - 0x55e67e9affca
             _ZN9xxxxxxxxxx6render7picking6Picker249draw<(&glium::vertex::buffer::VertexBuffer<xxxxxxxxxx::render::cube::CubeVertex>, glium::vertex::PerInstance),&glium::index::buffer::IndexBuffer<u16>,glium::uniforms::uniforms::UniformsStorage<[[f32; 4]; 4], glium::uniforms::uniforms::EmptyUniforms>>E at src/render/picking.rs:112
      17 - 0x55e67e90a5ab
             _ZN9xxxxxxxxxx6render8Renderer9game_loopE at src/render/mod.rs:157
      18 - 0x55e67e9f4a61
             _ZN9xxxxxxxxxx4mainE at src/main.rs:36
      19 - 0x55e67ece8894
             _ZN10sys_common6unwind3try6try_fn21h12978415923074316437E at <unknown>:??
      20 - 0x55e67ece6238
             __rust_try at <unknown>:??
      21 - 0x55e67ece852f
             _ZN2rt10lang_start20hbeb1bf39635abdcc9kxE at <unknown>:??
      22 - 0x55e67e9f4e99
             main at <unknown>:??
      23 - 0x7f573d1e060f
             __libc_start_main at <unknown>:??
      24 - 0x55e67e8b4908
             _start at <unknown>:??
      25 - 0x0
             <unknown> at <unknown>:??

    Debug message with high or medium severity: `GL_INVALID_FRAMEBUFFER_OPERATION in glReadPixels(incomplete framebuffer)`.
    Please report this error: https://github.com/tomaka/glium/issues
    Backtrace:
       1 - 0x55e67ebaa163
             _ZN9backtrace9backtrace9libunwind5traceE at /home/roxxik/.cargo/registry/src/github.com-88ac128001ac3a9a/backtrace-0.1.8/src/backtrace/libunwind.rs:54
             _ZN9backtrace9backtrace5traceE at /home/roxxik/.cargo/registry/src/github.com-88ac128001ac3a9a/backtrace-0.1.8/src/backtrace/mod.rs:67
       2 - 0x55e67ea3d5c9
             _ZN5glium7context22default_debug_callbackE at /home/roxxik/repos/glium/src/context/mod.rs:798
       3 - 0x55e67ea3d699
             _ZN156fn$LP$debug..Source$C$$u20$debug..MessageType$C$$u20$debug..Severity$C$$u20$u32$C$$u20$bool$C$$u20$$RF$str$RP$$u20$$u7b$context..default_debug_callback$u7d$21fn_pointer_shim.7158417ha294efbf0d04ac16E at <unknown>:??
       4 - 0x55e67eabe8b2
             _ZN372extern$u20$$u22$rust.call$u22$$u20$fn$LP$$RF$mut$u20$for$LT$$u27$r$GT$$u20$core..ops..FnMut$LP$debug..Source$C$$u20$debug..MessageType$C$$u20$debug..Severity$C$$u20$u32$C$$u20$bool$C$$u20$$RF$$u27$r$u20$str$RP$$u20$$u2b$$u20$$u27$static$C$$u20$$LP$debug..Source$C$$u20$debug..MessageType$C$$u20$debug..Severity$C$$u20$u32$C$$u20$bool$C$$u20$$RF$$u27$static$u20$str$RP$$RP$17object_shim.7754817h8d94c2ee80a483caE at <unknown>:??
       5 - 0x55e67eabe7e9
             _ZN5glium7context19init_debug_callback16callback_wrapperE at /home/roxxik/repos/glium/src/context/mod.rs:887
       6 - 0x55e67eabdf94
             _ZN7context19init_debug_callback16callback_wrapper20h60fcaf4a1f73ead9hHSE at <unknown>:??
       7 - 0x7f5735ee75e8
             <unknown> at <unknown>:??
       8 - 0x7f5735f7c7b1
             <unknown> at <unknown>:??
       9 - 0x55e67e8e893b
             _ZN9xxxxxxxxxx2gl2Gl10ReadPixelsE at target/debug/build/glium-1d288aab5bb0a2d4/out/gl_bindings.rs:12634
      10 - 0x55e67e8e7e5d
             _ZN9xxxxxxxxxx3ops4read88read<&glium::fbo::RegularAttachment,&glium::texture::pixel_buffer::PixelBuffer<i32>,i32>E at /home/roxxik/repos/glium/src/ops/read.rs:251
      11 - 0x55e67e8e6f1e
             _ZN9xxxxxxxxxx7texture3any19TextureAnyImage<'a>29raw_read_to_pixel_buffer<i32>E at /home/roxxik/repos/glium/src/texture/any.rs:1391
      12 - 0x55e67e8e6ae4
             _ZN9xxxxxxxxxx6render7picking6Picker4pickE at src/render/picking.rs:63
      13 - 0x55e67e90a1a0
             _ZN9xxxxxxxxxx6render8Renderer9game_loopE at src/render/mod.rs:139
      14 - 0x55e67e9f4a61
             _ZN9xxxxxxxxxx4mainE at src/main.rs:36
      15 - 0x55e67ece8894
             _ZN10sys_common6unwind3try6try_fn21h12978415923074316437E at <unknown>:??
      16 - 0x55e67ece6238
             __rust_try at <unknown>:??
      17 - 0x55e67ece852f
             _ZN2rt10lang_start20hbeb1bf39635abdcc9kxE at <unknown>:??
      18 - 0x55e67e9f4e99
             main at <unknown>:??
      19 - 0x7f573d1e060f
             __libc_start_main at <unknown>:??
      20 - 0x55e67e8b4908
             _start at <unknown>:??
      21 - 0x0
             <unknown> at <unknown>:??

    thread '<main>' panicked at 'index out of bounds: the len is 1 but the index is 1', src/libcollections/vec.rs:1106

**Comment by Roxxik** [comment]
I had an error in my code, the panic was my fault, but the traces still appear

**Comment by Roxxik** [comment]
Just fixed the bug from the panic and rerun with optirun, no problem at all.
Without i get those errors again.

From what i see it is mesa that does not support I32I32I32 (which I use in that app)
`Mesa 11.1.0 implementation error: gen7_update_renderbuffer_surface: renderbuffer format MESA_FORMAT_RGB_SINT32 unsupported`
