### ISSUE TITLE
BackendCreationError(OsError("eglCreateWindowSurface failed"))

### ISSUE THREAD

**Issue by dten** [tomaka/glium#1405]
I'm getting `eglCreateWindowSurface: native_window_api_connect (win=0xa9eb3c08) failed (0xffffffea) (already connected to another API?)` trying to create a new `Window` from a `WindowBuilder` on Android.

I throw away my Window on the Pause event and create a new one on Resume which works fine unless I pause and resume as fast as I can. If I do that I end up with the error at the end of this log, calling build_glium always results in this error until I restart the app. I can't figure out who's doign something wrong :( me, android-glue, glium or glutin

help

```
01-15 17:33:26.218  8521  8521 V threaded_app: NativeWindowCreated: 0xb4d3d300 -- 0xa9eb3c08
01-15 17:33:26.219  8521  8538 V threaded_app: APP_CMD_INIT_WINDOW
01-15 17:33:26.219  8521  8539 D RustAndroidGlueStdouterr: recv AndroidEvent: InitWindow
01-15 17:33:26.219  8521  8521 V threaded_app: Resume: 0xb4d3d300
01-15 17:33:26.219  8521  8538 V threaded_app: activityState=11
01-15 17:33:26.219  8521  8539 D RustAndroidGlueStdouterr: recv AndroidEvent: Resume
01-15 17:33:26.220  8521  8539 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I389a668de0)
01-15 17:33:26.220  8521  8539 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.28.00.04
01-15 17:33:26.220  8521  8539 I Adreno-EGL: Build Date: 10/24/15 Sat
01-15 17:33:26.220  8521  8539 I Adreno-EGL: Local Branch: mybranch15621148
01-15 17:33:26.220  8521  8539 I Adreno-EGL: Remote Branch: quic/LA.BF.1.1.3_rb1.3
01-15 17:33:26.220  8521  8539 I Adreno-EGL: Local Patches: NONE
01-15 17:33:26.220  8521  8539 I Adreno-EGL: Reconstruct Branch: NOTHING
01-15 17:33:26.220  8521  8521 V threaded_app: WindowFocusChanged: 0xb4d3d300 -- 1
01-15 17:33:26.220   230   956 E BufferQueueProducer: [com.example.native_activity/android.app.NativeActivity] connect(P): already connected (cur=1 req=1)
01-15 17:33:26.221  8521  8539 E libEGL  : eglCreateWindowSurface: native_window_api_connect (win=0xa9eb3c08) failed (0xffffffea) (already connected to another API?)
01-15 17:33:26.221  8521  8539 E libEGL  : eglCreateWindowSurface:456 error 3003 (EGL_BAD_ALLOC)
01-15 17:33:26.221  8521  8539 D RustAndroidGlueStdouterr: Failed to build_glium: BackendCreationError(OsError("eglCreateWindowSurface failed"))
```

**Comment by dten** [comment]
Just to give you an idea if it's me.. this is an approximation of my setup

```
let running = true;
'window_loop: loop {
    if !running {
        wait_for_resume();
        running = true;
    }

    let display = WindowBuilder::new().build_glium().unwrap();

    loop {
        if check_for_pause() {
            running = false;
            continue 'window_loop;
        }

        // update / draw using display.draw()
    }
}
```

Pause should cause the display to be Dropped, destroying the Context and Surface. but it seems by the time the resume is received this hasn't happened properly and a new one can't be made.

**Comment by tomaka** [comment]
Destroying the context should immediately result in `eglDestroySurface` being called.

What maybe happens is that the GPU hasn't finished drawing, which means that the surface is still somewhere in memory. After all the error really is "BAD_ALLOC", not "already connected".

If this hypothesis is true, you could try adding `display.finish()` right before or after `running = false`.

**Comment by tomaka** [comment]
I'm not so familiar with Android. I guess the real answer to this problem is somewhere in a "How to use OpenGL with Android?" article.

**Comment by dten** [comment]
Hey I came back to this eventually :) and I read a nice blog from NVidia how to best handle the life cycle in android since the it destroys everything from underneath you
https://developer.nvidia.com/fixing-common-android-lifecycle-issues-games

With that i implemented some that would listen for the resumed, focused and surface states and draw appropriately. Now it's mostly works but I get some errors when resuming the app some times.

I have tried calling display.finish() before throwing away the previous Facade but no luck. Tried checking / setting current before doing any draw calls but no luck.

this is some of my logcat log. you can see the error it says to report is `Error:glClear::failed to allocate CPU memory`.

I'm using glium 0.17 with glutin 0.7.4 and cargo-apk 0.1.7 and it's on a Galaxy S7 using opengl es 3.0

```
02-18 14:50:16.705  3706  3997 D WindowManager: finishDrawingWindow: Window{e910c12d0 u0 rust.gameboy/rust.gameboy.MainActivity} mDrawState=HAS_DRAWN
02-18 14:50:16.727 22516 22538 D RustAndroidGlueStdouterr: GAMEBOY LOG - display created
02-18 14:50:16.727 22516 22538 D RustAndroidGlueStdouterr: GAMEBOY LOG - vertex_buffer created
02-18 14:50:16.727 22516 22538 D RustAndroidGlueStdouterr: GAMEBOY LOG - index_buffer created
02-18 14:50:16.728 22516 22538 D RustAndroidGlueStdouterr: GAMEBOY LOG - program created
02-18 14:50:16.728 22516 22538 D RustAndroidGlueStdouterr: GAMEBOY LOG - s: true r: true f: false
02-18 14:50:16.728 22516 22538 D RustAndroidGlueStdouterr: GAMEBOY LOG - recv AndroidEvent: GainedFocus
02-18 14:50:16.741  3122  5162 E BufferQueueProducer: [rust.gameboy/rust.gameboy.MainActivity] dequeueBuffer: BufferQueue has no connected producer
02-18 14:50:16.742 22516 22537 D RustAndroidGlueStdouterr: Debug message with high or medium severity: `Error:glClear::failed to allocate CPU memory`.
02-18 14:50:16.742 22516 22537 D RustAndroidGlueStdouterr: Please report this error: https://github.com/tomaka/glium/issues
02-18 14:50:16.743 22516 22537 D RustAndroidGlueStdouterr: Backtrace:
02-18 14:50:16.789  3706  4077 D MdnieScenarioControlService:  packageName : rust.gameboy    className : rust.gameboy.MainActivity
02-18 14:50:16.804  5631  5631 D KP2AAF  : event: 32, package = rust.gameboy
02-18 14:50:16.812 22516 22537 D RustAndroidGlueStdouterr:    1 - 0x71dd46b923
02-18 14:50:16.812 22516 22537 D RustAndroidGlueStdouterr:          _ZN9backtrace9backtrace9libunwind5traceE at C:\Users\David\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.2.3\src\backtrace/libunwind.rs:54
02-18 14:50:16.812 22516 22537 D RustAndroidGlueStdouterr:          _ZN9backtrace9backtrace14trace<closure>E at C:\Users\David\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.2.3\src\backtrace/mod.rs:70
02-18 14:50:16.813 22516 22537 D RustAndroidGlueStdouterr:    2 - 0x71dd41880f
02-18 14:50:16.813 22516 22537 D RustAndroidGlueStdouterr:          _ZN5glium7context22default_debug_callbackE at C:\Users\David\.cargo\registry\src\github.com-1ecc6299db9ec823\glium-0.16.0\src\context/mod.rs:851
02-18 14:50:16.813 22516 22537 D RustAndroidGlueStdouterr:    3 - 0x71dd418c77
02-18 14:50:16.813 22516 22537 D RustAndroidGlueStdouterr:          _ZN5glium7context19init_debug_callback16callback_wrapperE at C:\Users\David\.cargo\registry\src\github.com-1ecc6299db9ec823\glium-0.16.0\src\context/mod.rs:938
02-18 14:50:16.813 22516 22537 D RustAndroidGlueStdouterr:    4 - 0x71d3b0c093
02-18 14:50:16.813 22516 22537 D RustAndroidGlueStdouterr:          <unknown> at <unknown>:??
02-18 14:50:16.813 22516 22537 D RustAndroidGlueStdouterr:    5 - 0x71d3b0ff7b
02-18 14:50:16.813 22516 22537 D RustAndroidGlueStdouterr:          <unknown> at <unknown>:??
02-18 14:50:16.813 22516 22537 D RustAndroidGlueStdouterr:    6 - 0x71d3ac2fd3
02-18 14:50:16.813 22516 22537 D RustAndroidGlueStdouterr:          <unknown> at <unknown>:??
02-18 14:50:16.813 22516 22537 D RustAndroidGlueStdouterr:    7 - 0x71d3ac0f1b
02-18 14:50:16.813 22516 22537 D RustAndroidGlueStdouterr:          <unknown> at <unknown>:??
02-18 14:50:16.813 22516 22537 D RustAndroidGlueStdouterr:    8 - 0x71d3abed8b
02-18 14:50:16.813 22516 22537 D RustAndroidGlueStdouterr:          <unknown> at <unknown>:??
02-18 14:50:16.814 22516 22537 D RustAndroidGlueStdouterr:    9 - 0x71dd42b3c7
02-18 14:50:16.814 22516 22537 D RustAndroidGlueStdouterr:          _ZN5glium3ops5clear5clearE at C:\Users\David\.cargo\registry\src\github.com-1ecc6299db9ec823\glium-0.16.0\src\ops/clear.rs:121
02-18 14:50:16.814 22516 22537 D RustAndroidGlueStdouterr:   10 - 0x71dd404e53
02-18 14:50:16.814 22516 22537 D RustAndroidGlueStdouterr:          _ZN5glium8{{impl}}5clearE at C:\Users\David\.cargo\registry\src\github.com-1ecc6299db9ec823\glium-0.16.0\src/lib.rs:1132
02-18 14:50:16.814 22516 22537 D RustAndroidGlueStdouterr:   11 - 0x71dd404edb
02-18 14:50:16.814 22516 22537 D RustAndroidGlueStdouterr:          _ZN5glium7Surface25clear_color<glium::Frame>E at C:\Users\David\.cargo\registry\src\github.com-1ecc6299db9ec823\glium-0.16.0\src/lib.rs:677
02-18 14:50:16.815 22516 22537 D RustAndroidGlueStdouterr:   12 - 0x71dd3f511b
02-18 14:50:16.815 22516 22537 D RustAndroidGlueStdouterr:          _ZN7gameboy7gameboy8{{impl}}10draw_frameE at C:\d\Documents\Repositories\TeamRocket\gameboyemulator\gameboy\src/gameboy.rs:157
02-18 14:50:16.815 22516 22537 D RustAndroidGlueStdouterr:   13 - 0x71dd3f59ef
02-18 14:50:16.815 22516 22537 D RustAndroidGlueStdouterr:          _ZN7gameboy7gameboy8{{impl}}8power_upE at C:\d\Documents\Repositories\TeamRocket\gameboyemulator\gameboy\src/gameboy.rs:302
02-18 14:50:16.815 22516 22537 D RustAndroidGlueStdouterr:   14 - 0x71dd3f18e7
02-18 14:50:16.815 22516 22537 D RustAndroidGlueStdouterr:          _ZN7gameboy6zelda2E at C:\d\Documents\Repositories\TeamRocket\gameboyemulator\gameboy\src/main.rs:40
02-18 14:50:16.815 22516 22537 D RustAndroidGlueStdouterr:   15 - 0x71dd50af7b
02-18 14:50:16.815 22516 22537 D RustAndroidGlueStdouterr:          _ZN12panic_unwind24__rust_maybe_catch_panicE at /buildslave/rust-buildbot/slave/nightly-dist-rustc-arm-android/build/src/libpanic_unwind/lib.rs:98
02-18 14:50:16.815 22516 22537 D RustAndroidGlueStdouterr:   16 - 0x71dd40ba5f
02-18 14:50:16.815 22516 22537 D RustAndroidGlueStdouterr:          _ZN3std9panicking12try<(),fn()>E at /buildslave/rust-buildbot/slave/nightly-dist-rustc-arm-android/build/src/libstd/panicking.rs:436
02-18 14:50:16.815 22516 22537 D RustAndroidGlueStdouterr:   17 - 0x71dd3f1857
02-18 14:50:16.815 22516 22537 D RustAndroidGlueStdouterr:          _ZN7gameboy4mainE at C:\d\Documents\Repositories\TeamRocket\gameboyemulator\gameboy\src/main.rs:44
02-18 14:50:16.816 22516 22537 D RustAndroidGlueStdouterr:   18 - 0x71dd50af7b
02-18 14:50:16.816 22516 22537 D RustAndroidGlueStdouterr:          _ZN12panic_unwind24__rust_maybe_catch_panicE at /buildslave/rust-buildbot/slave/nightly-dist-rustc-arm-android/build/src/libpanic_unwind/lib.rs:98
02-18 14:50:16.863 22516 22537 D RustAndroidGlueStdouterr:   19 - 0x71dd502fef
02-18 14:50:16.863 22516 22537 D RustAndroidGlueStdouterr:          _ZN3std9panicking12try<(),fn()>E at /buildslave/rust-buildbot/slave/nightly-dist-rustc-arm-android/build/src/libstd/panicking.rs:436
02-18 14:50:16.863 22516 22537 D RustAndroidGlueStdouterr:          _ZN3std5panic21catch_unwind<fn(),()>E at /buildslave/rust-buildbot/slave/nightly-dist-rustc-arm-android/build/src/libstd/panic.rs:361
02-18 14:50:16.863 22516 22537 D RustAndroidGlueStdouterr:          _ZN3std2rt10lang_startE at /buildslave/rust-buildbot/slave/nightly-dist-rustc-arm-android/build/src/libstd/rt.rs:57
02-18 14:50:16.864 22516 22537 D RustAndroidGlueStdouterr:   20 - 0x71dd536f93
02-18 14:50:16.864 22516 22537 D RustAndroidGlueStdouterr:          _ZN8glue_obj12android_main28_$u7b$$u7b$closure$u7d$$u7d$17hd8603e15b4d066acE at <unknown>:??
02-18 14:50:16.864 22516 22537 D RustAndroidGlueStdouterr:   21 - 0x71dd52dc5b
02-18 14:50:16.864 22516 22537 D RustAndroidGlueStdouterr:          _ZN23cargo_apk_injected_glue13android_main211main_thread17h0674b70d30e32c47E at <unknown>:??
02-18 14:50:16.864 22516 22537 D RustAndroidGlueStdouterr:   22 - 0x71ebb1e58f
02-18 14:50:16.864 22516 22537 D RustAndroidGlueStdouterr:          _ZL15__pthread_startPv at <unknown>:??
02-18 14:50:16.864 22516 22537 D RustAndroidGlueStdouterr:   23 - 0x71ebad2bf3
02-18 14:50:16.864 22516 22537 D RustAndroidGlueStdouterr:          __start_thread at <unknown>:??
02-18 14:50:16.864 22516 22537 D RustAndroidGlueStdouterr:   24 - 0x0
02-18 14:50:16.864 22516 22537 D RustAndroidGlueStdouterr:          <unknown> at <unknown>:??
02-18 14:50:16.865  3122  6677 E BufferQueueProducer: [rust.gameboy/rust.gameboy.MainActivity] dequeueBuffer: BufferQueue has no connected producer
```

Can you recommend something I should be looking into to see what's wrong?

I found someone who has their code online that does pretty much the same thing and has the same errors when resuming.
https://github.com/fmdkdd/asobiba/blob/10689046b7e4c0eb5f767a067498559d2b1eeb63/rust/tangled/src/display/display_android.rs

**Comment by dten** [comment]
I tried it on another phone, LG G3, also android with opengles 3.0

I get some different errors, the same behaviour as before now gives this error

```
02-18 16:19:48.622 13188 13209 D RustAndroidGlueStdouterr: GAMEBOY LOG - recv AndroidEvent: Resume
02-18 16:19:48.622 13188 13209 D RustAndroidGlueStdouterr: GAMEBOY LOG - s: false r: true f: false
02-18 16:19:48.639 13188 13188 V threaded_app: NativeWindowCreated: 0xb4cfe8e0 -- 0xaeb2bd08
02-18 16:19:48.639 13188 13206 V threaded_app: APP_CMD_INIT_WINDOW
02-18 16:19:48.639 13188 13209 D RustAndroidGlueStdouterr: GAMEBOY LOG - recv AndroidEvent: InitWindow
02-18 16:19:48.639 13188 13209 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I389a668de0)
02-18 16:19:48.639 13188 13209 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.28.00.04
02-18 16:19:48.639 13188 13209 I Adreno-EGL: Build Date: 10/24/15 Sat
02-18 16:19:48.639 13188 13209 I Adreno-EGL: Local Branch: mybranch15621148
02-18 16:19:48.639 13188 13209 I Adreno-EGL: Remote Branch: quic/LA.BF.1.1.3_rb1.3
02-18 16:19:48.639 13188 13209 I Adreno-EGL: Local Patches: NONE
02-18 16:19:48.639 13188 13209 I Adreno-EGL: Reconstruct Branch: NOTHING
02-18 16:19:48.640 13188 13188 V threaded_app: WindowFocusChanged: 0xb4cfe8e0 -- 1
02-18 16:19:48.649   248   345 E BufferQueueProducer: [rust.gameboy/rust.gameboy.MainActivity] cancelBuffer: BufferQueue has been abandoned
02-18 16:19:48.683  1173  1173 V PhoneStatusBar: setLightsOn(true)
02-18 16:19:48.769 13188 13209 W Adreno-ES20: <core_glGetInternalformativ:2312>: GL_INVALID_ENUM
02-18 16:19:48.770 13188 13209 D RustAndroidGlueStdouterr: GAMEBOY LOG - display created
02-18 16:19:48.770 13188 13208 D RustAndroidGlueStdouterr: glium has triggered an OpenGL error during initialization. Please report this error: https://github.com/tomaka/glium/issues
02-18 16:19:48.770 13188 13209 D RustAndroidGlueStdouterr: GAMEBOY LOG - vertex_buffer created
02-18 16:19:48.770 13188 13209 D RustAndroidGlueStdouterr: GAMEBOY LOG - index_buffer created
02-18 16:19:48.779 13188 13209 D RustAndroidGlueStdouterr: GAMEBOY LOG - program created
02-18 16:19:48.779 13188 13209 D RustAndroidGlueStdouterr: GAMEBOY LOG - s: true r: true f: false
02-18 16:19:48.779 13188 13209 D RustAndroidGlueStdouterr: GAMEBOY LOG - recv AndroidEvent: GainedFocus
02-18 16:19:53.201  1864  2039 I DeviceStateChecker: screenOn: true, isCharging: true
02-18 16:19:58.488   265   340 E ThermalEngine: [GPU_MON] 8 percent. Current Sampling Time is 4 sec
```


and if i minimise and resume really quick i get 

```
-18 16:21:04.916 13188 13209 D RustAndroidGlueStdouterr: GAMEBOY LOG - s: false r: true f: false
-18 16:21:04.937 13188 13188 V threaded_app: NativeWindowCreated: 0xb4cfe8e0 -- 0xaeb2bd08
-18 16:21:04.937 13188 13206 V threaded_app: APP_CMD_INIT_WINDOW
-18 16:21:04.938 13188 13209 D RustAndroidGlueStdouterr: GAMEBOY LOG - recv AndroidEvent: InitWindow
-18 16:21:04.938 13188 13209 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I389a668de0)
-18 16:21:04.938 13188 13209 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.28.00.04
-18 16:21:04.938 13188 13209 I Adreno-EGL: Build Date: 10/24/15 Sat
-18 16:21:04.938 13188 13209 I Adreno-EGL: Local Branch: mybranch15621148
-18 16:21:04.938 13188 13209 I Adreno-EGL: Remote Branch: quic/LA.BF.1.1.3_rb1.3
-18 16:21:04.938 13188 13209 I Adreno-EGL: Local Patches: NONE
-18 16:21:04.938 13188 13209 I Adreno-EGL: Reconstruct Branch: NOTHING
-18 16:21:04.938 13188 13188 V threaded_app: WindowFocusChanged: 0xb4cfe8e0 -- 1
-18 16:21:04.938   248 10942 E BufferQueueProducer: [rust.gameboy/rust.gameboy.MainActivity] connect(P): already connected (cur=1 req=1)
-18 16:21:04.938 13188 13209 E libEGL  : eglCreateWindowSurface: native_window_api_connect (win=0xaeb2bd08) failed (0xffffffea) (already connected to another API?)
-18 16:21:04.938 13188 13209 E libEGL  : eglCreateWindowSurface:456 error 3003 (EGL_BAD_ALLOC)
-18 16:21:04.939 13188 13209 D RustAndroidGlueStdouterr: GAMEBOY LOG - main paniced
-18 16:21:04.940 13188 13208 D RustAndroidGlueStdouterr: thread 'main' panicked at 'build_glium err: BackendCreationError(OsError("eglCreateWindowSurface failed"))', /buildslave/rust-buildbot/slave/nightly-dist-rustc-arm-android/build/src/libcore/result.rs:868
-18 16:21:04.940 13188 13208 D RustAndroidGlueStdouterr: note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by dten** [comment]
I thought this may be to do with android-glue passing a message to us that we should finish with the surface and then immediately returning from the callback (at which point the system would destroy it before we on the other thread had finished) so i changed it to be synchronous. it didn't help 👎
