### ISSUE TITLE
Instanced Drawing with a Buffer Slice Overflows

### ISSUE THREAD

**Issue by c0gent** [tomaka/glium#1507]
Performing an instanced draw call using a slice as the source of vertices can cause a subtraction overflow. 

Excerpt from [the full gist](https://gist.github.com/c0gent/73dfac1c7a6b9207354a3ec6fcb9f376):
```
     // Drawing the entire models vertex buffer (all three triangles, a
     // total of 9 vertices * 7 instances) works just fine:
     surface.draw((&model_buf, instance_buf.per_instance().unwrap()),
         &indices, &program, &uniforms, &params).unwrap();

     // Likewise, drawing only the first triangle, or any number of
     // vertices from the start of the models vertex buffer, is fine:
     surface.draw((model_buf.slice(0..3).unwrap(), instance_buf.per_instance().unwrap()),
         &indices, &program, &uniforms, &params).unwrap();

     // As soon as we attempt to draw the second triangle model (or any
     // other range of vertices which does not start at the beginning of
     // the buffer), we get a subtraction overflow:
     surface.draw((model_buf.slice(3..6).unwrap(), instance_buf.per_instance().unwrap()),
         &indices, &program, &uniforms, &params).unwrap();
```

This appears to be related to the process of binding the buffer as a VAO and re-zeroing indices of the slice but I don't know enough about how this optimization should work in this edge case to offer any help fixing it.

P.S. I realize that storing each model in its own buffer is the more conventional (and possibly overall better) approach.

**Comment by jimblandy** [comment]
FWIW, reproduced in Glium 0.21.0. Adapted sources [here][gist]. Output from a debug build:
```
RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `/home/jimb/rust/pdxrust-glium/instancing/target/debug/instancing`
thread 'main' panicked at 'attempt to subtract with overflow', /home/jimb/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.21.0/src/vertex_array_object.rs:184:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:72
   8: core::panicking::panic
             at libcore/panicking.rs:51
   9: glium::vertex_array_object::Binder::bind
             at /home/jimb/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.21.0/src/vertex_array_object.rs:184
  10: glium::ops::draw::draw
             at /home/jimb/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.21.0/src/ops/draw.rs:156
  11: <glium::Frame as glium::Surface>::draw
             at /home/jimb/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.21.0/src/lib.rs:1191
  12: instancing::main
             at src/main.rs:102
  13: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  14: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  15: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  16: std::rt::lang_start_internal
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  17: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  18: main
  19: __libc_start_main
  20: _start
```
[gist]: https://gist.github.com/jimblandy/925f10a48fdd3958288f9d63a564d066
