### ISSUE TITLE
`tessellation` example instantly segfaults on start

### ISSUE THREAD

**Issue by zetok** [tomaka/glium#1521]
glium: cd1bab4f6b7c3b48391289b3a10be115f660b252

GPU: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii PRO [Radeon R9 290]
Kernel: 4.6.3 with with a [custom patch revert](https://github.com/zetok/linux/commit/5cf988c19590162338fc53cb5abb6589372709b8) that makes freeze during gaming ~non-existent
Driver: radeon
Mesa: 12.0.1
Xorg: 1.17.4

```
Starting program: /home/zetok/working/delete/glium/target/debug/examples/tessellation 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe8cf7700 (LWP 7836)]
The current tessellation level is 5 ; use the Up and Down keys to change it

Program received signal SIGSEGV, Segmentation fault.
0x00007fffe99489c0 in llvm::Value::getName() const ()
   from /usr/lib64/libLLVMCore.so.3.7
(gdb) bt
#0  0x00007fffe99489c0 in llvm::Value::getName() const ()
   from /usr/lib64/libLLVMCore.so.3.7
#1  0x00007ffff03c7cc7 in (anonymous namespace)::SITypeRewriter::visitCallInst(llvm::CallInst&) () from /usr/lib64/libLLVMAMDGPUCodeGen.so.3.7
#2  0x00007ffff03c8a1e in (anonymous namespace)::SITypeRewriter::runOnFunction(llvm::Function&) () from /usr/lib64/libLLVMAMDGPUCodeGen.so.3.7
#3  0x00007fffe9922fad in llvm::FPPassManager::runOnFunction(llvm::Function&) ()
   from /usr/lib64/libLLVMCore.so.3.7
#4  0x00007fffe9923443 in llvm::FPPassManager::runOnModule(llvm::Module&) ()
   from /usr/lib64/libLLVMCore.so.3.7
#5  0x00007fffe99236f1 in llvm::legacy::PassManagerImpl::run(llvm::Module&) ()
   from /usr/lib64/libLLVMCore.so.3.7
#6  0x00007fffeabccffd in LLVMTargetMachineEmit(LLVMOpaqueTargetMachine*, LLVMOpaqueModule*, llvm::raw_pwrite_stream&, LLVMCodeGenFileType, char**) ()
   from /usr/lib64/libLLVMTarget.so.3.7
#7  0x00007fffeabcd2ce in LLVMTargetMachineEmitToMemoryBuffer ()
   from /usr/lib64/libLLVMTarget.so.3.7
#8  0x00007ffff1ebedd4 in radeon_llvm_compile (M=M@entry=0x7fffe7d3fb80, 
    binary=binary@entry=0x7fffe7d6d990, gpu_family=<optimized out>, 
    tm=tm@entry=0x7ffff6d19c00, debug=debug@entry=0x7ffff6c8b8f0)
    at /var/tmp/portage/media-libs/mesa-12.0.1/work/mesa-12.0.1/src/gallium/drivers/radeon/radeon_llvm_emit.c:235
#9  0x00007ffff1e301b0 in si_compile_llvm (sscreen=sscreen@entry=0x7ffff6d19000, 
    binary=binary@entry=0x7fffe7d6d990, conf=conf@entry=0x7fffe7d6d9e8, 
    tm=tm@entry=0x7ffff6d19c00, mod=mod@entry=0x7fffe7d3fb80, 
    debug=debug@entry=0x7ffff6c8b8f0, processor=3, 
    name=0x7ffff1f95100 "TGSI shader")
    at /var/tmp/portage/media-libs/mesa-12.0.1/work/mesa-12.0.1/src/gallium/drivers/radeonsi/si_shader.c:6166
#10 0x00007ffff1e3218b in si_compile_tgsi_shader (
    sscreen=sscreen@entry=0x7ffff6d19000, tm=tm@entry=0x7ffff6d19c00, 
    shader=shader@entry=0x7fffe7d6d900, is_monolithic=is_monolithic@entry=true, 
    debug=debug@entry=0x7ffff6c8b8f0)
    at /var/tmp/portage/media-libs/mesa-12.0.1/work/mesa-12.0.1/src/gallium/drivers/radeonsi/si_shader.c:6561
#11 0x00007ffff1e32ae9 in si_shader_create (sscreen=0x7ffff6d19000, 
    tm=0x7ffff6d19c00, shader=shader@entry=0x7fffe7d6d900, 
    debug=debug@entry=0x7ffff6c8b8f0)
    at /var/tmp/portage/media-libs/mesa-12.0.1/work/mesa-12.0.1/src/gallium/drivers/radeonsi/si_shader.c:7527
#12 0x00007ffff1e3e01d in si_shader_select_with_key (ctx=ctx@entry=0x7ffff6c8b000, 
    state=0x7ffff6c8bd88, key=0x7fffffffa0b0)
    at /var/tmp/portage/media-libs/mesa-12.0.1/work/mesa-12.0.1/src/gallium/drivers/radeonsi/si_state_shaders.c:993
#13 0x00007ffff1e3e170 in si_shader_select (ctx=ctx@entry=0x7ffff6c8b000, 
    state=state@entry=0x7ffff6c8bd88)
    at /var/tmp/portage/media-libs/mesa-12.0.1/work/mesa-12.0.1/src/gallium/drivers/radeonsi/si_state_shaders.c:1021
#14 0x00007ffff1e3f5fb in si_update_shaders (sctx=sctx@entry=0x7ffff6c8b000)
    at /var/tmp/portage/media-libs/mesa-12.0.1/work/mesa-12.0.1/src/gallium/drivers/radeonsi/si_state_shaders.c:1955
#15 0x00007ffff1e3adb6 in si_draw_vbo (ctx=0x7ffff6c8b000, info=0x7fffffffa500)
    at /var/tmp/portage/media-libs/mesa-12.0.1/work/mesa-12.0.1/src/gallium/drivers/---Type <return> to continue, or q <return> to quit---
radeonsi/si_state_draw.c:905
#16 0x00007ffff1ce59e4 in u_vbuf_draw_vbo (mgr=0x7ffff6d3ae00, 
    info=<optimized out>)
    at /var/tmp/portage/media-libs/mesa-12.0.1/work/mesa-12.0.1/src/gallium/auxiliary/util/u_vbuf.c:1163
#17 0x00007ffff1b199ea in st_draw_vbo (ctx=0x7fffe8103500, prims=<optimized out>, 
    nr_prims=1, ib=0x7fffffffa5e0, index_bounds_valid=<optimized out>, 
    min_index=4294967295, max_index=4294967295, tfb_vertcount=0x0, stream=0, 
    indirect=0x0)
    at /var/tmp/portage/media-libs/mesa-12.0.1/work/mesa-12.0.1/src/mesa/state_tracker/st_draw.c:251
#18 0x00007ffff1ad902a in vbo_validated_drawrangeelements (
    ctx=ctx@entry=0x7fffe8103500, mode=mode@entry=14, 
    index_bounds_valid=index_bounds_valid@entry=0 '\000', 
    start=start@entry=4294967295, end=end@entry=4294967295, count=count@entry=3, 
    type=5123, indices=0x0, basevertex=0, numInstances=1, baseInstance=0)
    at /var/tmp/portage/media-libs/mesa-12.0.1/work/mesa-12.0.1/src/mesa/vbo/vbo_exec_array.c:849
#19 0x00007ffff1ad956b in vbo_exec_DrawElements (mode=14, count=3, type=5123, 
    indices=0x0)
    at /var/tmp/portage/media-libs/mesa-12.0.1/work/mesa-12.0.1/src/mesa/vbo/vbo_exec_array.c:985
#20 0x00005555555c79c9 in glium::gl::{{impl}}::DrawElements (self=0x7ffff6d59d50, 
    mode=14, count=3, type_=5123, indices=0x0)
    at /home/zetok/working/delete/glium/target/debug/build/glium-4f7704a0c05aa3b5/out/gl_bindings.rs:8631
#21 0x00005555555ab880 in glium::ops::draw::draw<glium::uniforms::uniforms::UniformsStorage<i32, glium::uniforms::uniforms::UniformsStorage<[[f32; 4]; 4], glium::uniforms::uniforms::EmptyUniforms>>,&glium::vertex::buffer::VertexBuffer<tessellation::main::Vertex>> (context=0x7ffff6d59d50, framebuffer=..., 
    vertex_buffers=0x7fffffffd558, indices=..., program=0x7fffffffc9e0, 
    uniforms=0x7fffffffc480, draw_parameters=0x7fffffffc170, dimensions=...)
    at /home/zetok/working/delete/glium/src/ops/draw.rs:258
#22 0x00005555555a9853 in glium::{{impl}}::draw<&glium::vertex::buffer::VertexBuffer<tessellation::main::Vertex>,&glium::index::buffer::IndexBuffer<u16>,glium::uniforms::uniforms::UniformsStorage<i32, glium::uniforms::uniforms::UniformsStorage<[[f32; 4]; 4], glium::uniforms::uniforms::EmptyUniforms>>> (self=0x7fffffffc318, 
    vertex_buffer=0x7fffffffd558, index_buffer=0x7fffffffcf28, 
    program=0x7fffffffc9e0, uniforms=0x7fffffffc480, 
    draw_parameters=0x7fffffffc170)
    at /home/zetok/working/delete/glium/src/lib.rs:1168
#23 0x00005555555a7deb in tessellation::main::{{closure}} ()
    at /home/zetok/working/delete/glium/examples/tessellation.rs:148
#24 0x00005555555a7825 in tessellation::support::start_loop<closure> (callback=...)
    at /home/zetok/working/delete/glium/examples/support/mod.rs:23
#25 0x000055555557a37d in tessellation::main ()
    at /home/zetok/working/delete/glium/examples/tessellation.rs:133
#26 0x00005555557b5029 in std::panicking::try::call::hca715a47aa047c49 ()
#27 0x00005555557bcfcc in __rust_try ()
#28 0x00005555557bcf6f in __rust_maybe_catch_panic ()
#29 0x00005555557b4acf in std::rt::lang_start::h162055cb2e4b9fe7 ()
#30 0x00005555555c8eba in main ()
    at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libc---Type <return> to continue, or q <return> to quit---
ore/result.rs:29
```
`t a a bt full`: https://gist.github.com/zetok/3a2341b457fc58a0358981b65a78c506

related: https://github.com/OsnaCS/plantex/issues/200

**Comment by tomaka** [comment]
Well, that's a bug in the driver since the stacktrace is in the shader compiler.
