### ISSUE TITLE
"Failed to get root window"

### ISSUE THREAD

**Issue by raingloom** [tomaka/glium#1585]
I'm trying to run the following example:

```rust
#[macro_use]
extern crate glium;

use glium::*;

fn main() {
    let display = glium::glutin::WindowBuilder::new()
        .with_dimensions(1024,1024)
        .with_title("Hai")
        .build_glium()
        .unwrap();
    loop {
/*        for ev in display.poll_events() {
            match ev {
                glium::glutin::Event::Closed => return,
                _ => ()
            }
        }*/
    }
}
```
Running it with cargo (from Emacs) gives me this output (backtrace enabled). I have no idea what the stream of eights is.
```
-*- mode: cargo-process; default-directory: "~/deymoh/" -*-
Cargo-Process started at Sat Apr  1 21:45:05

cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.1 secs
     Running `target/debug/deymoh`
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
thread 'main' panicked at 'Failed to get root window: XError { description: "GLXBadFBConfig", error_code: 178, request_code: 155, minor_code: 34 }', /checkout/src/libcore/result.rs:859
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:761
   1: glutin::platform::platform::x11::Window::new
             at /home/rain/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.4/src/platform/linux/x11.rs:215
   2: glutin::platform::platform::api_dispatch::Window::new
             at /home/rain/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.4/src/platform/linux/api_dispatch.rs:100
   3: glutin::window::<impl glutin::WindowBuilder<'a>>::build
             at /home/rain/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.4/src/window.rs:224
   4: glium::backend::glutin_backend::GlutinWindowBackend::new
             at /home/rain/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.16.0/src/backend/glutin_backend.rs:262
   5: glium::backend::glutin_backend::<impl glium::DisplayBuild for glutin::WindowBuilder<'static>>::build_glium_debug
             at /home/rain/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.16.0/src/backend/glutin_backend.rs:150
   6: glium::DisplayBuild::build_glium
             at /home/rain/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.16.0/src/lib.rs:1240
   7: deymoh::main
             at ./src/main.rs:7

Cargo-Process exited abnormally with code 101 at Sat Apr  1 21:45:06
```

System info:
```
Arch Linux + Mesa
i3 window manager
Thinkpad T400 with old Intel graphics
```
I actually do see a window pop up for a fraction of a second. AFAIK there are no problems with my system, I have used it before to play some old games.

**Comment by rosenk** [comment]
I have the same problem with ubuntu 16.04 on hp laptop 6710b. I beleave it has OpenGL 2.1 hardware. Is this version of OpenGL supported?

**Comment by raingloom** [comment]
Fixed it by forcing an older version of OprnGL, but the error message could be clearer about what's going wrong, so I'll edit the issue to that.

**Comment by rosenk** [comment]
Please be more specific, how to force an older version. I need this worksround too.

**Comment by raingloom** [comment]
I checked the output of glxinfo and it told me the supported version.

Here is how you force a specific version:
```rust
let display = glium::glutin::WindowBuilder::new()
        .with_dimensions(1024,1024)
        .with_title("Hai")
        .with_gl(glutin::GlRequest::GlThenGles{
            opengl_version : (2, 1),
            opengles_version : (2, 1),
        })
        .build_glium()
        .unwrap();
```
