### ISSUE TITLE
Panic for: 'GL_INVALID_ENUM in CreateShader(type)'

### ISSUE THREAD

**Issue by TheNeikos** [tomaka/glium#495]
The full panic message:

```
neikos@celestias-palace ~/p/r/bloqs> cargo run                                                                        < 101
     Running `target/bloqs`
thread 'glium rendering thread' panicked at 'Debug message with high or medium severity: `GL_INVALID_ENUM in CreateShader(type)`.
Please report this error: https://github.com/tomaka/glium/issues', /home/neikos/.cargo/git/checkouts/glium-cee1c79709e4d1bd/master/src/lib.rs:1679
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:743
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:743
stack backtrace:
   1:     0x7f3fb90d3a00 - sys::backtrace::write::h49b06c4e5fa1765dZTA
   2:     0x7f3fb90e6ce0 - failure::on_fail::h128a61ca90111ec2JFJ
   3:     0x7f3fb90c7110 - rt::unwind::begin_unwind_inner::h142cc6242e7988934jJ
   4:     0x7f3fb90c7c20 - rt::unwind::begin_unwind_fmt::h9f6d3c7c640c0421AiJ
   5:     0x7f3fb90e6c00 - rust_begin_unwind
   6:     0x7f3fb9111d60 - panicking::panic_fmt::h21faf6f60b06c77cSvw
   7:     0x7f3fb8f48b00 - result::Result<T, E>::unwrap::h9973605888421199388
   8:     0x7f3fb8f6bc60 - context::Context::exec::h5691806902112660613
   9:     0x7f3fb8f6bbf0 - program::Shader.Drop::drop::h69a661d47cbc9de6MVb
  10:     0x7f3fb8f75d10 - program..Shader::glue_drop.47209::hdaea61c331f08e91
  11:     0x7f3fb8f75510 - vec::Vec<T>.Drop::drop::h7714566669021697601
  12:     0x7f3fb8f754e0 - collections..vec..Vec<program..Shader>::glue_drop.47206::h69557029b08d62be
  13:     0x7f3fb8f72760 - program::Program::from_source_impl::h50ebb5f0c0f30fd0zfc
  14:     0x7f3fb8f15d60 - program::Program::new::h2802733595079189804
  15:     0x7f3fb8ede4b0 - main::hc77c6503431c4754Cba
  16:     0x7f3fb90eb590 - rust_try_inner
  17:     0x7f3fb90eb580 - rust_try
  18:     0x7f3fb90e8890 - rt::lang_start::h61cf7984fd279964KzJ
  19:     0x7f3fb8ede990 - main
  20:     0x7f3fb7d2e710 - __libc_start_main
  21:     0x7f3fb8ede380 - _start
  22:                0x0 - <unknown>
thread panicked while panicking. aborting.
An unknown error occurred

To learn more, run the command again with --verbose.
```

```
neikos@celestias-palace ~/p/r/bloqs> rustc -V                                                                         < 101
rustc 1.0.0-nightly (3ef8ff1f8 2015-02-12 00:38:24 +0000)
```

I used the tesselation example. This does not happen for the other examples (so far)

**Comment by tomaka** [comment]
Thanks!

It's bug a when calling `CreateShader`. Instead of properly checking whether the hardware supports tessellation shaders, glium just calls the function and checks the return type.

**Comment by TheNeikos** [comment]
That's what I figured, but since it explicitly tells to open an issue I went ahead with that.

**Comment by TheNeikos** [comment]
Also, it seems to panic as it hits the geometry shader, which is probably the same problem, but just to be sure.
