### ISSUE TITLE
Crash on OS X

### ISSUE THREAD

**Issue by palango** [tomaka/glium#623]
When I try to run examples from master on OS X 10.10 it always crashes. Output follows, tell me if you need more information.

```
cargo run --example triangle --verbose                                                 12:54:27
       Fresh libc v0.1.2
       Fresh genmesh v0.0.13
       Fresh bitflags v0.1.1
       Fresh khronos_api v0.0.5
       Fresh clock_ticks v0.0.4
       Fresh rustc-serialize v0.2.15
       Fresh log v0.2.5
       Fresh rand_macros v0.1.4
       Fresh rustc-serialize v0.3.1
       Fresh gl_common v0.0.4
       Fresh core_foundation v0.1.0 (https://github.com/servo/rust-core-foundation#c577bd64)
       Fresh obj v0.0.11
       Fresh cocoa v0.1.1 (https://github.com/servo/rust-cocoa#ca3441a1)
       Fresh xml-rs v0.1.20
       Fresh rand v0.1.4
       Fresh rand v0.2.0
       Fresh core_graphics v0.1.0 (https://github.com/servo/rust-core-graphics#e169ad38)
       Fresh gl_generator v0.0.19
       Fresh nalgebra v0.2.5 (https://github.com/sebcrozet/nalgebra#32f20788)
       Fresh num v0.1.15 (https://github.com/rust-lang/num#fbd7d81b)
       Fresh cgmath v0.0.7 (https://github.com/bjz/cgmath-rs#5d6717cb)
       Fresh image v0.2.0-alpha.11 (https://github.com/PistonDevelopers/image#e6228fc3)
       Fresh glutin v0.0.7 (http://github.com/tomaka/glutin#277b66a7)
       Fresh glium v0.0.3 (file:///Users/paul/Projects/rust/glium)
     Running `target/examples/triangle`
thread '<main>' panicked at 'not yet implemented', /Users/paul/.cargo/git/checkouts/glutin-666c1766c69e6584/master/src/cocoa/mod.rs:591
thread '<main>' panicked at 'not yet implemented', /Users/paul/.cargo/git/checkouts/glutin-666c1766c69e6584/master/src/cocoa/mod.rs:591
stack backtrace:
   1:        0x10f3b4dfd - sys::backtrace::write::h4102628905e599dfKDA
   2:        0x10f3c7dfc - panicking::on_panic::hc3e357b7ac1634e3MsJ
   3:        0x10f3a78e9 - rt::unwind::begin_unwind_inner::h53ac351c4bf63bfaibJ
   4:        0x10f39f92e - rt::unwind::begin_unwind::h10757872431940520363
   5:        0x10f3a10d1 - winimpl::Window::is_current::hae50f2ce83618c28nRa
   6:        0x10f2ded39 - window::Window::is_current::h2e768ad37b364603Q3d
   7:        0x10f2dece9 - backend::glutin_backend::GlutinWindowBackend.Backend::is_current::h4ee139538ab61961nmv
   8:        0x10f390757 - backend::Rc<T>.Backend::is_current::h6359082584172852721
   9:        0x10f27c35f - context::Context::make_current::h116b49871da79a5aYKw
  10:        0x10f27d5d5 - DisplayImpl.Drop::drop::ha4cd3c85f13e6040gMb
  11:        0x10f27d4dc - DisplayImpl::glue_drop.50800::hebbdddcaa8474369
  12:        0x10f27d114 - rc::Rc<T>.Drop::drop::h14706040146723856490
  13:        0x10f27cf0d - alloc..rc..Rc<DisplayImpl>::glue_drop.50746::h0c4c7e3121592c07
  14:        0x10f27cedd - Display::glue_drop.50743::hc0ab68870029e9ac
  15:        0x10f359d1e - glutin..WindowBuilder<'static>.DisplayBuild::build_glium::h07b0942b3cc6a990vsb
  16:        0x10f24f837 - main::h70cb624b45880e58Qia
  17:        0x10f3c9b58 - rust_try_inner
  18:        0x10f3c9b45 - rust_try
  19:        0x10f3c8727 - rt::lang_start::hcc79e4b22a4ec7532mJ
  20:        0x10f24fc2e - main
thread panicked while panicking. aborting.
Process didn't exit successfully: `target/examples/triangle` (signal: 4)
```

**Comment by tomaka** [comment]
Thanks! Glium has recently started using a new function from glutin, and I totally forgot that glutin doesn't have an implementation for this on OS/X yet.

**Comment by tomaka** [comment]
If you need a work-around, you can replace `build_glium()` with `build_glium_unchecked()` (this is an unsafe function though). It should work as long as you don't do weird things like multiple contexts.

**Comment by ryanstew** [comment]
tomaka/glutin#316 includes a fix for this that's working for me.

**Comment by ryanstew** [comment]
tomaka/glutin#316 has been merged, so this should be resolved.

**Comment by tomaka** [comment]
Closing. Please reopen if it's still an issue.
