### ISSUE TITLE
cargo test aborts: dri2_allocate_textures: Assertion `*zsbuf' failed

### ISSUE THREAD

**Issue by dcampbell24** [tomaka/glium#794]
When I run `cargo test` the process aborts:

```
     Running target/debug/attrs-b106654a2dbc69c4

running 51 tests
test attribute_types_mismatch ... FAILED
test attribute_float_i16 ... FAILED
test attribute_float_i8 ... FAILED
test attribute_float_f32 ... FAILED
test attribute_float_i32 ... FAILED
test attribute_float_u8 ... FAILED
test attribute_float_u32 ... FAILED
test attribute_float_u16 ... FAILED
radeon: Failed to allocate a buffer:
radeon:    size      : 65536 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 4
radeon:    flags     : 4
radeon: Failed to allocate a buffer:
radeon:    size      : 65536 bytes
radeon:    alignment : 4096 bytes
radeon:    domains   : 4
radeon:    flags     : 4
EE ../../../../../../src/gallium/drivers/radeon/r600_texture.c:560 r600_texture_allocate_htile - Failed to create buffer object for htile buffer.
radeon: Failed to allocate a buffer:
radeon:    size      : 1572864 bytes
radeon:    alignment : 32768 bytes
radeon:    domains   : 4
radeon:    flags     : 20
radeon: Failed to allocate a buffer:
radeon:    size      : 1572864 bytes
radeon:    alignment : 32768 bytes
radeon:    domains   : 4
radeon:    flags     : 20
attrs-b106654a2dbc69c4: ../../../../../../src/gallium/state_trackers/dri/dri2.c:610: dri2_allocate_textures: Assertion `*zsbuf' failed.
Process didn't exit successfully: `/home/david/git/glium/target/debug/attrs-b106654a2dbc69c4` (signal: 6)
```

My graphics card is `Advanced Micro Devices, Inc. [AMD/ATI] Curacao XT [Radeon R9 270X]`

**Comment by tomaka** [comment]
Ouch!

You could run one of the tests individually to see what the reason for failure is?
Just execute `target/debug/attrs-b106654a2dbc69c4 test attribute_float_u8` for example.

**Comment by dcampbell24** [comment]
I just updated and ran again and got
```
     Running target/debug/attrs-b106654a2dbc69c4

running 51 tests
LLVM ERROR: 'main' label emitted multiple times to assembly file
```

When I run `./target/debug/attrs-b106654a2dbc69c4 attribute_float_u8` I get
```
$ ./target/debug/attrs-b106654a2dbc69c4 attribute_float_u8

running 1 test
test attribute_float_u8 ... FAILED

failures:

---- attribute_float_u8 stdout ----
	thread 'attribute_float_u8' panicked at 'called `Result::unwrap()` on an `Err` value: IncompatibleOpenGl("OpenGL implementation doesn\'t support depth or depth-stencil textures")', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:729



failures:
    attribute_float_u8

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libtest/lib.rs:253
```

Some more info:
```
$ rustc --version
rustc 1.1.0-nightly (c4b23aec4 2015-04-29) (built 2015-04-29)

$ sudo lshw -c video
[sudo] password for david: 
  *-display               
       description: VGA compatible controller
       product: Curacao XT [Radeon R9 270X]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:01:00.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=radeon latency=0
       resources: irq:35 memory:e0000000-efffffff memory:f7c00000-f7c3ffff ioport:e000(size=256) memory:f7c40000-f7c5ffff
  *-display
       description: Display controller
       product: Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 06
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm bus_master cap_list
       configuration: driver=i915 latency=0
       resources: irq:36 memory:f7400000-f77fffff memory:d0000000-dfffffff ioport:f000(size=64)

```

**Comment by tomaka** [comment]
What does `glxinfo` say?

You should run your tests with `--no-default-features` in order to avoid that `IncompatibleOpenGl` error.

**Comment by dcampbell24** [comment]
There is a lot of output: https://gist.github.com/dcampbell24/612b38fcc820de79e330

```
$ cargo test --no-default-features

...

     Running target/debug/attrs-b106654a2dbc69c4

running 51 tests
LLVM ERROR: 'main' label emitted multiple times to assembly file
attrs-b106654a2dbc69c4: ../../../../../../src/egl/drivers/dri2/egl_dri2.c:492: dri2_setup_screen: Assertion `dri2_dpy->swrast' failed.
Process didn't exit successfully: `/home/david/git/glium/target/debug/attrs-b106654a2dbc69c4` (signal: 6)

**Comment by tomaka** [comment]
Oh, it's my fault. Apparently an unwanted change slipped it, and you're using OpenGL ES 2, which is only half supported.

I'll fix this in https://github.com/tomaka/glium/pull/797

**Comment by tomaka** [comment]
Could you try again now?

**Comment by dcampbell24** [comment]
I now get the following:
```
$ cargo test 
...
     Running target/debug/attrs-d94356d36432cf35

running 51 tests
Process didn't exit successfully: `/home/david/git/glium/target/debug/attrs-d94356d36432cf35` (signal: 4)

$ cargo test --no-default-features
...
     Running target/debug/attrs-d94356d36432cf35

running 51 tests
LLVM ERROR: 'main' label emitted multiple times to assembly file
LLVM ERROR: 'main' label emitted multiple times to assembly file
```
Then I tried again in a new directory in case there were old files causing issues and got
```
$ cargo test --no-default-features
...
     Running target/debug/attrs-4183a7b18ed4d17e

running 51 tests
test attribute_types_mismatch ... ok
LLVM ERROR: 'main' label emitted multiple times to assembly file
```

**Comment by tomaka** [comment]
I don't really see an explanation expect a bug in your drivers :-/
